### PR TITLE
configure native comp and webrender in ci

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by harryfei** [comment]
We can have 2 job in CI.  One is for building `emacs-ng` without webrender and another is for building with `webrender`.

**Comment by brotzeit** [comment]
Do we really need this ? Why not test everything together ?

**Comment by harryfei** [comment]
If we build with `webrender` option, `gtk` or `macosx` gui related code will not be built. We need to continue to check those graphic backends' code.

**Comment by brotzeit** [comment]
Hmm, yeah I forgot you are also modifying code that's related to this.

**Comment by brotzeit** [comment]
I opened another pull request that replaces this one (#200). After we have merged it, we can also include webrender.

**Pull request closed without merging**
