### PR TITLE
add straight.el/use-package as git submodules

### PR DESCRIPTION
**Pull request by declanqian**
#98

### CODE REVIEW

**Comment by brotzeit** [comment]
Thanks for the pull request! Please give us some time to review your changes.

FYI I just looked if there's progress on merging use-package into emacs, but it seems nothing happened. @declanqian we should keep the related issue open as a reminder that we have to remove use-package when it was merged upstream.

**Comment by declanqian** [comment]
Sure, no problem. Take your time.

> we should keep the related issue open 
as a reminder that we have to remove use-package when it was merged upstream.

That does make sense. Let's do that.

**Comment by DavidDeSimone** [comment]
What is the origin of the changes in ldef-boot.el? Is this an older version behind upstream for compatibility?

**Comment by declanqian** [comment]
It's a copy of the generated `loaddefs.el` from lisp dir. This file is only
used in the early stage of the build process I think. Should be OK to leave
it out though. @DavidDeSimone

**Comment by declanqian** [comment]
It should an output of `./admin/update_autogen`.
Since we're using git submodule, the script is broken.
Anyway, just left that changes out.

**Comment by DavidDeSimone** [comment]
Thanks for the PR, this looks good to me. I will defer to the team members that have a stronger knowledge of these packages but it's a 👍 for me.

**Review by kidd — APPROVED** [review]
Triggered the tests. looks good to me

**Comment by brotzeit** [comment]
I think we should mention this somewhere in the docs, any ideas ?

**Comment by black7375** [comment]
https://emacs-ng.github.io/emacs-ng/#features
How about adding a built-in packages?

**Comment by brotzeit** [comment]
> How about adding a built-in packages?

Maybe it's better to add a section under "Home" since all the other features are based on rust.

I'll open a seperate doc issue.

**Comment by brotzeit** [comment]
@declanqian Thanks!

**Pull request merged**
