### PR TITLE
update rustfmt target

### PR DESCRIPTION
**Pull request by wolf4ood**
I've added two lines of docs about `rustfmt` target. I'm not sure the `tests` section is the right place.
I was not sure where to place this info :)

### CODE REVIEW

**Comment by wolf4ood** [comment]
Closes #296

**Comment by jman-schief** [comment]
LGTM, @brotzeit did you have anything else for #296?

**Review by DavidDeSimone — APPROVED** [review]

**Review by harryfei — APPROVED** [review]

**Comment by brotzeit** [comment]
> LGTM, @brotzeit did you have anything else in mind for #296?

Looks good to me :+1:

**Comment by brotzeit** [comment]
Btw, thanks @wolf4ood ;)

**Pull request merged**
