### PR TITLE
Replace io::Error with anyhow::Error

### PR DESCRIPTION
**Pull request by wolf4ood**
:wave:  this PR fixes the issue  [#175 ](https://github.com/emacs-ng/emacs-ng/issues/175) by using the re-exported `anyhow::Error` by Deno.

I'm not sure yet how to test regressions or eventual breaking changes caused by this.  I tried to eval some scripts and seems fine.
If you have specific tests to run let me know :)

Thanks

### CODE REVIEW

**Comment by DavidDeSimone** [comment]
I'm on email right now but - Approved, LTGM. Thanks for the contribution!

**Comment by DavidDeSimone** [comment]
Also with respect to tests, I'm confident in our current test set to
catch any basic regressions. Since all CI tests are passing I feel
good with this PR.

**Comment by apiraino** [comment]
cool @wolf4ood thanks :-)

**Comment by jman-schief** [comment]
cool @wolf4ood thanks

**Pull request merged**
