### PR TITLE
Enable dynamic modules to directly read current buffer's text

### PR DESCRIPTION
**Pull request by ubolonton**
Since we want to be ABI-compatible with dynamic modules written for vanilla Emacs, we don't add more functions to `emacs_env`.

Instead, we provide a registry of named native functions that can be looked up at run time. We call these `ng-module functions`. Unlike normal module functions, they have globally stable addresses, which should be looked up once, at module load time (in `emacs_module_init`).

I made a [quick prototype](https://github.com/ubolonton/emacs-tree-sitter/commit/381cf5cdd300bf2df347f53f163d0d9d59635c36) that shows how to use this in `emacs-tree-sitter`. Some quick-n-dirty tests show up to 2x speedups.

### CODE REVIEW

**Comment by brotzeit** [comment]
Looks really cool! Can you add some sentences to our docs ? I would also link emacs-tree-sitter.

**Comment by ubolonton** [comment]
Yeah, I'll write up a short doc with example.

**Review by DavidDeSimone — APPROVED** [review]
Code LGTM, agree it would be good to have some docs on this.

**Review by harryfei — APPROVED** [review]

**Review by DavidDeSimone — APPROVED** [review]
LGTM Code Wise

**Comment by ubolonton** [comment]
I've added some docs for it.

The example looks a bit too long. Once `emacs-module-rs` adds support for this, it will be more concise.

**Comment by brotzeit** [comment]
Nice!

**Pull request merged**
