### PR TITLE
move javascript code to seperate crate

### LINKED ISSUE #271: Move deno related code to seperate crate
Can be started after #270 was merged. @DavidDeSimone how do we handle the async code, add an additional crate ?

### PR DESCRIPTION
**Pull request by brotzeit**
close #271

### CODE REVIEW

**Comment by brotzeit** [comment]
```
Run cd test/js/
  cd test/js/
  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
  cd ../../rust_src/src
  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
  cd ../../
  shell: /usr/bin/bash -e {0}
  env:
    CC: clang
    CXX: clang++
    CPP: clang -E
    CFLAGS:  -g1 -O2 -fuse-ld=lld -lxcb-render -lxcb-xfixes -lxcb-shape
    CXXFLAGS:  -g1 -O2 -fuse-ld=lld
    AR: llvm-ar
    AS: llvm-as
    RANLIB: llvm-ranlib
    CARGO_INCREMENTAL: 0
    RUSTFLAGS: -Zshare-generics=y -Cdebuginfo=1 -Copt-level=0 -Clink-arg=-fuse-ld=lld
    LD: lld
    NPROC: nproc
Debugger entered--Lisp error: (error "Error in deno command 'deno fmt --check': No targe...")
  deno("fmt" "--check")
  eval((deno "fmt" "--check") t)
  command-line-1(("--eval" "(deno \"fmt\" \"--check\")"))
  command-line()
  normal-top-level()

Error: Process completed with exit code 255.
```

@DavidDeSimone can you help me out ?

**Comment by DavidDeSimone** [comment]
I should be able to get to this tomorrow but it should be an easy fix - we just need to change the directory we run (deno "fmt") in to reflect our new file path to prelim.js

**Comment by DavidDeSimone** [comment]
For some reason I'm unable to push to your branch. This is likely user error on my part. This is the patch to fix CI, if @brotzeit or any other contributor wants to push to this branch.

```diff
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index c75933fbdb..bf2e913d04 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -202,9 +202,9 @@ jobs:
               run: |
                   cd test/js/
                   ../../src/emacs --batch --eval '(deno "fmt" "--check")'
-                  cd ../../rust_src/crates/js/src/
-                  ../../../../src/emacs --batch --eval '(deno "fmt" "--check")'
-                  cd ../../../../
+                  cd ../../rust_src/src
+                  ../../src/emacs --batch --eval '(deno "fmt" "--check")'
+                  cd ../../
 
             - name: run js tests
               run: |
```

**Comment by brotzeit** [comment]
I'll do the cleanup in the next pull request. Are the other changes ok ?

**Pull request merged**
