### PR TITLE
Merge efaed29f3d

### PR DESCRIPTION
**Pull request by brotzeit**
```diff
unmerged   src/Makefile.in
@@@ -571,9 -517,7 +572,13 @@@ LIBES = $(LIBS) $(W32_LIBS) $(LIBS_GNUS
     $(FREETYPE_LIBS) $(FONTCONFIG_LIBS) $(HARFBUZZ_LIBS) $(LIBOTF_LIBS) $(M17N_FLT_LIBS) \
     $(LIBGNUTLS_LIBS) $(LIB_PTHREAD) $(GETADDRINFO_A_LIBS) $(LCMS2_LIBS) \
     $(NOTIFY_LIBS) $(LIB_MATH) $(LIBZ) $(LIBMODULES) $(LIBSYSTEMD_LIBS) \
++<<<<<<< HEAD
 +   $(JSON_LIBS) $(LIBGMP) $(LIBGCCJIT) \
 +   $(XCB_LIBS) \
 +   $(LIB_REMACS)
++=======
+    $(JSON_LIBS) $(LIBGMP) $(LIBGCCJIT_LIBS)
++>>>>>>> upstream
  
  ## FORCE it so that admin/unidata can decide whether this file is
  ## up-to-date.  Although since charprop depends on bootstrap-emacs,
unmerged   src/lisp.h
@@@ -4116,7 -4118,7 +4118,11 @@@ extern Lisp_Object Vautoload_queue
  extern Lisp_Object Vrun_hooks;
  extern Lisp_Object Vsignaling_function;
  extern Lisp_Object inhibit_lisp_code;
++<<<<<<< HEAD
 +extern Lisp_Object signal_or_quit (Lisp_Object, Lisp_Object, bool);
++=======
+ extern bool signal_quit_p (Lisp_Object);
++>>>>>>> upstream
  
  /* To run a normal hook, use the appropriate function from the list below.
     The calling convention:
```

### CODE REVIEW

**Comment by harryfei** [comment]
Webrender failed with missing xcb. It's so wired.

**Comment by harryfei** [comment]
You forget to change commit hash in README.

**Comment by harryfei** [comment]
https://github.com/emacs-ng/emacs-ng/blob/1b63e048eb7c48b755245863601d4b94652ed378/src/Makefile.in#L575

You deleted this line when merge.

**Comment by brotzeit** [comment]
I think I should include a diff in the pull request for future upstream merges, thanks.

**Review by harryfei — APPROVED** [review]

**Pull request merged**
