### PR TITLE
Nix build fix

### LINKED ISSUE #454: Building with Nix Flakes failed
**Describe the bug**
Building with nix flakes failed:
image

**To Reproduce**
I tried to install EmacsNg using nix flakes, but it failed b/c of sha mismatch.

**Expected behavior**
Installing emacsng with nix flakes should work.

**OS**
Nixos

### PR DESCRIPTION
**Pull request by declantsien**
- ~Unclear about the way nix used to work. Nix today requires a hash if we use fetchGit.
Not sure how we pass that hash if the build is triggered by CI.
So instead I just use ./. (the checked out source as src).~

- ~Secondly I see we used to vendor cargo sources using nix on build time. But fetchTarball also
need to specify a hash (fixed-output).~

~There would be a lot of overhead for just updating the hash string.
So instead, I put the vendor-ed source in the repo.
This way, there is just a little overhead for developers when updating dependencies. Instead of
just updating Cargo.toml, they also needs to vendor the sources and update .cargo/config.~

~This is the way how Firefox/chromium are dealing with Rust crates. see:
https://github.com/mozilla/gecko-dev/blob/893a8f062ec6144c84403fbfb0a57234418b89cf/python/mozbuild/mozbuild/vendor/vendor_rust.py
https://github.com/chromium/chromium/tree/main/third_party/rust#rust-third-party-code~

- ~Unclear about the licenses issues though.~

Close #454 #442 #410 #312

### CODE REVIEW

**Comment by GTrunSec** [comment]
`vendor cargo sources` is not bad for me.  I also have a refactor work in mind, and maybe someday I will put it on. 

- LGTM

**Comment by harryfei** [comment]
I don't think it's a good idea.

**Comment by GTrunSec** [comment]
We can temporarily turn off the CI of nix-build, and then turn it on when I find free time to refactor it.

**Comment by declantsien** [comment]
> I think it's bad practice. It makes the repo unnecessary huge.

I am hesitated with huge repo size too. I am gonna drop this.

> We can temporarily turn off the CI of nix-build,

Disabled using github interface. See here
https://github.com/emacs-ng/emacs-ng/actions/workflows/checks.yaml

> and then turn it on when I find free time to refactor it.

Looking forward to it.

**Comment by declantsien** [comment]
Today, I realized that nix has support for automatically [vendoring source using Cargo.lock file](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#vendoring-of-dependencies-vendoring-of-dependencies).
I tried it out. It works!
Also I removed the formatting changes. Would you like to give this a review? @GTrunSec

**Comment by GTrunSec** [comment]
> https://github.com/declantsien/emacs-ng/blob/nix-build-fix/flake.nix#L152
nice, we did the same thing.

**Review by GTrunSec — APPROVED** [review]

**Comment by Atemu** [comment]
This is great, thanks!

**Pull request merged**
