### PR TITLE
ci: Also build release for webrender version

### LINKED ISSUE #215: Also generate release package for webrender

### PR DESCRIPTION
**Pull request by kiennq**
Fix #215

### CODE REVIEW

**Comment by kiennq** [comment]
@brotzeit Currently `--with-webrender` failed with 
```
Compiling deno v1.8.1 (https://github.com/DavidDeSimone/deno?branch=emacs-ng#cadc58d7)
error[E0432]: unresolved imports `emacs::bindings::Qbold`, `emacs::bindings::Qextra_bold`, `emacs::bindings::Qextra_light`, `emacs::bindings::Qitalic`, `emacs::bindings::Qlight`, `emacs::bindings::Qnil`, `emacs::bindings::Qnormal`, `emacs::bindings::Qoblique`, `emacs::bindings::Qsemi_bold`, `emacs::bindings::Qultra_bold`, `emacs::bindings::Qwr`
  --> src/webrender_backend/font.rs:20:9
```
https://github.com/kiennq/emacs-ng/runs/2317880842?check_suite_focus=true#step:3:2423

Might be related to the checked-in generated binding in #201?

**Comment by brotzeit** [comment]
Yeah, we fixed that in https://github.com/emacs-ng/emacs-ng/pull/205/commits/5366ad5068a586dd1a7aec1447f8132bca39e4eb

**Comment by kiennq** [comment]
@harryfei One thing I notice with webrender is this line is spewed out when configuring `What toolkit should Emacs use? none`
Is that expected?

**Comment by kiennq** [comment]
> Yeah, we fixed that in #205

I found the commit, cherry-pick to here. It would not cause conflict even when we merge both of them

**Comment by black7375** [comment]
> One thing I notice with webrender is this line is spewed out when configuring What toolkit should Emacs use? none
Is that expected?

Not sure, webrender seems to replace toolkit. https://github.com/emacs-ng/emacs-ng/issues/163#issuecomment-802633986 https://github.com/emacs-ng/emacs-ng/issues/184#issuecomment-803533523

**Comment by harryfei** [comment]
> @harryfei One thing I notice with webrender is this line is spewed out when configuring `What toolkit should Emacs use? none`
> Is that expected?

@kiennq @black7375 It's normal. `webrender` is a window system backend in `emacs-ng`. 

The toolkit means x gui toolkit in `emacs` (options: none, gtk, gtk3).

We have x, webrender, ns (macOSX) and win32 window systems in `emacs-ng`.

**Comment by kiennq** [comment]
The release will look like this https://github.com/kiennq/emacs-ng/releases/tag/v0.1.2

**Review by brotzeit — APPROVED** [review]
LGTM

**Pull request merged**
