### PR TITLE
Upstream feature/native-comp for mac build

### PR DESCRIPTION
**Pull request by black7375**
Recent commit(79b8b6ca45ad707d86244882430e275efd95cdb9) resolves the Mac's build issue. #195

### CODE REVIEW

**Comment by black7375** [comment]
Hmm...There seems to be still a problem.

https://github.com/black7375/emacs-ng/actions/runs/699932043
```
alloc.c:3160:7: error: implicit declaration of function 'unload_comp_unit' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      unload_comp_unit (cu);
      ^
1 error generated.
make[1]: *** [alloc.o] Error 1
```

**Comment by black7375** [comment]
I think we can include. src/comp.h
https://github.com/emacs-ng/emacs-ng/blob/bba450fab1e2a2ccc2dca40a6e5408596236d4a7/src/comp.h#L81

I recommend fixing this problem from the original.
Has anyone ever sent a patch to the FSF?

**Comment by brotzeit** [comment]
Hopefully it's easier for us to fix this bug(and also to avoid this kind of issues in the future) when we have osx included in our build. I opened #200.

**Comment by kidd** [comment]
native-comp got a fix for the warning: https://lists.gnu.org/archive/html/emacs-diffs/2021-04/msg00014.html

**Comment by black7375** [comment]
I was about to go to bed, so I'll wake up tomorrow and merge it.

https://github.com/emacs-mirror/emacs/commit/978afd788fd0496540f715b83f18ed390ca8d5a4

**Pull request merged**
