### PR TITLE
rename remacs_sys module

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by harryfei** [comment]
Can we have a new name instead of `generated`?

**Comment by brotzeit** [comment]
Sure what do you have in mind ?

**Comment by yyoncho** [comment]
IMHO `remacs_sys` should be `lisp` or `emacs`.

**Comment by harryfei** [comment]
I like `sys` or `emacs`

**Comment by brotzeit** [comment]
Keep in mind that the generated stuff will be pulled into another crate.

**Comment by brotzeit** [comment]
And that the generated bindings also contain non-lisp stuff.

**Comment by brotzeit** [comment]
I'm working on a PR that also covers this.

**Pull request closed without merging**
