### PR TITLE
Upstream feature/native-comp

### PR DESCRIPTION
**Pull request by black7375**
## Description
The build was successful and the environment is as follows:

```shell
## uname -a
# Linux black7375-pc 5.10.18-1-MANJARO #1 SMP PREEMPT Tue Feb 23 18:07:15 UTC 2021 x86_64 GNU/Linux

## rustc --version
# rustc 1.52.0-nightly (f5d8117c3 2021-03-16)

## clang --version
# clang version 11.1.0
# Target: x86_64-pc-linux-gnu

./autogen.sh
./configure --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc --libexecdir=/usr/lib --localstatedir=/var \
            --with-sound=alsa --with-modules --with-wide-int --with-xft --with-harfbuzz --with-cairo \
            --with-x-toolkit=gtk3 --with-xwidgets \
            --without-gconf --without-gsettings \
            --with-native-compilation
make -j"$(nproc)" CARGO_FLAGS="-j$(nproc)"
sudo make install
```

image
It runs in my environment.

## Warning
1. **Recreate `ChangeLog`**

I put `ChangeLog.3` back in because I plan to create a workflow that automatically merges upstream in the future.

2. **Webrender**

It doesn't work with option `webrender`, and it doesn't work with master in my environment.
```shell
--with-webrender
```
The `master` branch is the same.
More info: #184

3. **The most important thing**

There are many changes, so make sure to test them.

## TODO
I can't promise you I'll do it right away, but...
I want to do this kind of work.

- Creating a github action that automatically merges in [master branch](https://github.com/emacs-mirror/emacs/tree/master) and [feature/native-comp branch](https://github.com/emacs-mirror/emacs/tree/feature/native-comp)
- Build and release action
  - I'm thinking about it for AUR first.
- Combine [feature/pgtk branch](https://github.com/emacs-mirror/emacs/tree/feature/pgtk) for linux #163
  - It's not a common part, so I think we need a dedicated branch rather than a master. Like `target/linux`?

### CODE REVIEW

**Comment by brotzeit** [comment]
Thanks for your work! It also works for me.
If you want an invite to the project, give this post a thumbs up.

> I put ChangeLog.3 back in because I plan to create a workflow that automatically merges upstream in the future.

What do you mean by automatically ? I'm asking because we still need the possibility to edit merges, since we did touch some C code and I suppose we will need to apply more modifications for features like webrender.

 > There are many changes, so make sure to test them.

I only tested some basic stuff since I heard that there have been issues with some packages recently. There's not much more we can do when merging upstream. I think it makes sense to tag certain commits where things seem to be stable, but this project will stay unstable and should be considered as playground for people who want to add new features and try new features. But I try to use it as my daily driver to see if I notice issues.

> Combine feature/pgtk branch for linux #163

    It's not a common part, so I think we need a dedicated branch rather than a master. Like target/linux?

Sure. I didn't take a look at the amount of changes they applied, but if we have a feature branch for some time and things seem to work, maybe we can also merge it. But maybe there are potential issues I don't see.

First thing when you intend to work on something, would ideally be to open an issue so we can discuss it.

**Comment by brotzeit** [comment]
Let's give others a few days to test it, then I would merge it.

**Comment by DavidDeSimone** [comment]
Concur with @brotzeit of letting this be tested for a few days and then merge.

**Comment by black7375** [comment]
> What do you mean by automatically ?

This is an action that applies changes from the remote regularly (for example, on a weekly basis).
When this action is created, it will be updated automatically according to the schedule unless a conflict occurs.

> Sure. I didn't take a look at the amount of changes they applied, but if we have a feature branch for some time and things seem to work, maybe we can also merge it. But maybe there are potential issues I don't see.

 I think we need a new branch if the work is done because it can be unstable.

> First thing when you intend to work on something, would ideally be to open an issue so we can discuss it.

Yes, This PR was started simply to see if Upstream is possible, but if I do something else, I'll open the issue.

---

Thank you for the wonderful project!!

**Comment by kiennq** [comment]
Btw, shouldn't in latest `nativecomp` branch, the build flag has been changed from `--with-nativecomp` to `--with-native-compilation`?

**Comment by black7375** [comment]
I made a mistake by copying and putting the command in the issue #184.
Currently corrected it. The compilation itself is fine.

> Btw, shouldn't in latest nativecomp branch, 

Then, do we need a development branch, not a `master`?

> the build flag has been changed from `--with-nativecomp` to `--with-native-compilation`?

Yes. This is the latest branch option.

Should I change it to `--with-nativecomp`?
Or I can replace the document and test with `--with-native-compilation`.

**Comment by black7375** [comment]
The invitation was well received.
Thank you. :smile_cat:

**Comment by brotzeit** [comment]
Can we merge this ?

**Comment by black7375** [comment]
There is still one consideration.(`--with-nativecomp` / `--with-native-compilation`)
https://github.com/emacs-ng/emacs-ng/blob/e7c4c721becd65fb1bc2507662880561c83eb30c/docs/faq.md#L13-L14

https://github.com/emacs-ng/emacs-ng/blob/7f4c75d249cf4a09ff69a2c80a84a3514ebd50d0/build_emacs_ng.sh#L12-L15

I think it's better to follow the latest options, but I haven't applied them because there's no agreement in thread yet.
> Should I change it to `--with-nativecomp`?
Or I can replace the document and test with `--with-native-compilation`.

**Comment by kiennq** [comment]
I think we just update to use latest flag and it should be fine.

**Comment by black7375** [comment]
Updated to latest emacs-ng commit to fix the build script.

**Pull request merged**
