### PR TITLE
Fix winit scaling issues

### LINKED ISSUE #493: Winit/WR scaling code is broken
Issue created based on [comment](https://github.com/emacs-ng/emacs-ng/issues/488#issuecomment-1445407191)

> the scaling code is broken, but it always was with winit. (Causes some weird bug with the cursor as clearly two different values for scale are being used internally.)

It should be specific when using winit as windowing implementation.

### PR DESCRIPTION
**Pull request by declantsien**
Close #493

### CODE REVIEW

**Comment by 2e0byo** [comment]
This breaks mouse position when scale != 1.

**Comment by declantsien** [comment]
> This breaks mouse position when scale != 1.

Ive tested it with
`
swaymsg output eDP-1 scale 1`
swaymsg output eDP-1 scale 2`
`
Both are working fine. Are you stil having issue with winit/tao? @2e0byo

**Comment by 2e0byo** [comment]
Yes.  Mouse position with tao is off by the scale factor.  Funny as this looks like doing the scaling properly.  Under Hyprland; I'll try with weston in a moment.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> Yes.  Mouse position with tao is off by the scale factor.  Funny as this looks like doing the scaling properly.  Under Hyprland; I'll try with weston in a moment.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/pull/501#issuecomment-1451713680
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

Ok, Just tried again with tao. It does have issue. Will fix when I got time.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> Yes.  Mouse position with tao is off by the scale factor.  Funny as this looks like doing the scaling properly.  Under Hyprland; I'll try with weston in a moment.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/pull/501#issuecomment-1451713680
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

This[0], the latest should fix tao. 


[0] https://github.com/emacs-ng/emacs-ng/compare/1055b432c4d2ae865b88279c3417919dbb330c2e..a092673b5ff434f605b08ca73692bf9aa3a404a3

**Comment by 2e0byo** [comment]
> This[0], the latest should fix tao. [0] https://github.com/emacs-ng/emacs-ng/compare/1055b432c4d2ae865b88279c3417919dbb330c2e..a092673b5ff434f605b08ca73692bf9aa3a404a3

It does, but where on earth is `OutputInner.cursor_position` actually defined?  I feel thoroughly stupid.  Anyhow it works.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

>> This[0], the latest should fix tao. [0] https://github.com/emacs-ng/emacs-ng/compare/1055b432c4d2ae865b88279c3417919dbb330c2e..a092673b5ff434f605b08ca73692bf9aa3a404a3
>
> It does, but where on earth is `OutputInner.cursor_position` actually defined?  I feel thoroughly stupid.  Anyhow it works.
>
>
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/pull/501#issuecomment-1451802810
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

It's here `rust_src/crates/webrender/src/window_system/winit/output.rs`.
Nah, I am feeling that our code may be somehow over-engineered.

**Comment by 2e0byo** [comment]
In this case I really was being daft, I'd missed that it's just a struct member rather than a function... and then it's set from the cursor move event in `winit/term.rs`. Which is much better than polling anyhow.  thank you!

**Comment by 2e0byo** [comment]
We still need to handle [`ScaleFactorChanged`](https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.ScaleFactorChanged) events (e.g.if a window is dragged from one monitor to another).   The event gets the new size so it might be as simple as calling `output.resize()`, or we might need to trigger a rebuild.

**Comment by declantsien** [comment]
2e0byo ***@***.***> writes:

> In this case I really was being daft, I'd missed that it's just a struct member rather than a function... and then it's set from the cursor move event in `winit/term.rs`. Which is much better than polling anyhow.  thank you!
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/emacs-ng/emacs-ng/pull/501#issuecomment-1451847181
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

This is probably a bug from tao. They have `cursor_position` associated
with `Window` which has type `PhysicalPosition`. I expected they update
the value as the one we now received from `CursorMove` event. Apparently
it not the same when `scale_factor` been other than 1. Anyway, I don't
want to dig to the bottom of it. Glad it's working now.

**Comment by 2e0byo** [comment]
The code paths are actually completely independent.  I opened an issue at tao: https://github.com/tauri-apps/tao/issues/708

**Pull request merged**
